### ISSUE TITLE
Posible errata en clase aeródronomo

### ISSUE THREAD

**Issue by dportoles** [oeg-upm/ontology-BTN100#11]
Se cita en esta clase la definición de aeródronomo, pero creo que en realidad es una errata y es un aeródromo
 
https://github.com/oeg-upm/ontology-BTN100/blob/1914043984b7e3315386f52560ff9532fe11ec57/OnToology/btn100.owl/documentation/ontology.xml#L1219

Aerodrónomo, AFAIK, es para drones y no parece que sea lo que se hace referencia.

**Comment by ocorcho** [comment]
@paoespinozarias lo arregla en la próxima versión de la ontología

**Comment by paoespinozarias** [comment]
Fixed in pull request #13
