### ISSUE TITLE
Errata en URL de codelist competencia

### ISSUE THREAD

**Issue by dportoles** [oeg-upm/ontology-BTN100#12]
Aquí https://github.com/oeg-upm/ontology-BTN100/blob/1914043984b7e3315386f52560ff9532fe11ec57/OnToology/btn100.owl/documentation/ontology.ttl#L151

se referencia a  https://datos.ign.es/page/kos/transportes/competencia
cuando en realidad creo que es https://datos.ign.es/page/kos/transportes/competencia-via

**Comment by ocorcho** [comment]
Lo modificaremos en la próxima versión de la documentación de la ontología. 

En lugar de https://datos.ign.es/page/kos/transportes/competencia-via usaremos https://datos.ign.es/kos/transportes/competencia-via (puesto que es la URI del skos:ConceptScheme.

**Comment by dportoles** [comment]
Cierto, sin el /page

**Comment by paoespinozarias** [comment]
Fixed in pull request #13
